/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddUser.java
 *
 * Created on 23/04/2010, 02:22:50
 */
package com.siscomercio.frames;

import javax.swing.JFrame;
import com.siscomercio.managers.DatabaseManager;
import com.siscomercio.utilities.SystemUtil;

/**
 * $Revision$
 * $Author$
 * $Date$
 * @author Rayan
 */
public class AddUser extends JFrame
{
    private static final long serialVersionUID = 1L;

    /** Creates new form AddUser */
    public AddUser()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelSobrenome = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        confirmarSenha = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoSobrenome = new javax.swing.JTextField();
        campoLogin = new javax.swing.JTextField();
        campoConfirma = new javax.swing.JPasswordField();
        campoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adcionar Usuário");
        getContentPane().setLayout(null);

        jPanel1.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jPanel3.setLayout(null);

        labelNome.setFont(new java.awt.Font("Times New Roman", 1, 14));
        labelNome.setText("Nome");
        jPanel3.add(labelNome);
        labelNome.setBounds(80, 30, 35, 20);

        labelSobrenome.setFont(new java.awt.Font("Times New Roman", 1, 14));
        labelSobrenome.setText("Sobrenome");
        jPanel3.add(labelSobrenome);
        labelSobrenome.setBounds(46, 60, 69, 20);

        labelLogin.setFont(new java.awt.Font("Times New Roman", 1, 14));
        labelLogin.setText("Login");
        jPanel3.add(labelLogin);
        labelLogin.setBounds(80, 90, 35, 20);

        labelSenha.setFont(new java.awt.Font("Times New Roman", 1, 14));
        labelSenha.setText("Senha");
        jPanel3.add(labelSenha);
        labelSenha.setBounds(80, 130, 38, 20);
        jPanel3.add(jSlider1);
        jSlider1.setBounds(80, 250, 192, 25);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(120, 300, 87, 25);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(220, 300, 77, 25);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getRootPane().setDefaultButton(jButton1);
        jPanel3.add(jButton1);
        jButton1.setBounds(20, 300, 93, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setText("Nível de Acesso");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(120, 220, 95, 17);

        confirmarSenha.setFont(new java.awt.Font("Times New Roman", 1, 14));
        confirmarSenha.setText("Confirma Senha");
        jPanel3.add(confirmarSenha);
        confirmarSenha.setBounds(20, 170, 101, 17);
        jPanel3.add(campoNome);
        campoNome.setBounds(130, 30, 90, 20);
        jPanel3.add(campoSobrenome);
        campoSobrenome.setBounds(130, 60, 90, 20);
        jPanel3.add(campoLogin);
        campoLogin.setBounds(130, 90, 90, 20);
        jPanel3.add(campoConfirma);
        campoConfirma.setBounds(130, 170, 90, 20);
        jPanel3.add(campoSenha);
        campoSenha.setBounds(130, 130, 90, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 340, 350);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-345)/2, (screenSize.height-381)/2, 345, 381);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
       if(campoLogin.getText().equals(""))
       {
            SystemUtil.showErrorMsg("o login nao deve ser em branco", true);
            return;
       }

        if(String.valueOf(campoSenha.getPassword()).equalsIgnoreCase((String.valueOf(campoConfirma.getPassword()))))
        {
            DatabaseManager.insertUser(campoLogin.getText(), String.valueOf(campoSenha.getPassword()));
        }
        else
        {
            SystemUtil.showErrorMsg("os campos de senha devem coincidir", true);
            campoSenha.setText("");
            campoConfirma.setText("");
        }

}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        campoNome.setText("");
        campoLogin.setText("");
        campoSenha.setText("");
        campoConfirma.setText("");
        campoSobrenome.setText("");
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        dispose();
}//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new AddUser().setVisible(true);
            }

        });
    }

    private void resetCampos()
    {
        campoNome.setText("");
        campoLogin.setText("");
        campoSenha.setText("");
        campoSobrenome.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField campoConfirma;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoSobrenome;
    private javax.swing.JLabel confirmarSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSobrenome;
    // End of variables declaration//GEN-END:variables
}
