/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siscomercio.model.view.frames;

import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Rayan
 */
public class FrameSplashScreen extends javax.swing.JFrame
{
    /**
     * Creates new form FrameSplashScreen
     */
    public FrameSplashScreen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barraProgresso = new javax.swing.JProgressBar();
        labelInformacao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setForeground(new java.awt.Color(0, 204, 255));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVersao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVersao.setText("versionInfo");
        jPanel2.add(labelVersao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Versão:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel2.add(barraProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 306, 10));

        labelInformacao.setText("Carregando....");
        jPanel2.add(labelInformacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siscomercio/model/view/icones/splash.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 220));

        getContentPane().add(jPanel2);

        setSize(new java.awt.Dimension(453, 238));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrameSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new FrameSplashScreen().setVisible(true);
            }
        });
    }

    public JProgressBar getBarraProgresso()
    {
        return barraProgresso;
    }

    public JLabel getLabelInformacao()
    {
        return labelInformacao;
    }

    public JLabel getLabelVersao()
    {
        return labelVersao;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelInformacao;
    private javax.swing.JLabel labelVersao;
    // End of variables declaration//GEN-END:variables
}
