/*
 * TrocaSenha.java
 *
 * Created on 03/05/2010, 12:01:48
 */
package com.siscomercio.model.view.frames;

import com.siscomercio.controller.managers.DatabaseManager;
import com.siscomercio.utilities.SystemUtil;

/**
 * $Revision: 123 $
 * $Author: rayan_rpg@hotmail.com $
 * $Date: 2010-05-03 14:39:12 -0300 (seg, 03 mai 2010) $
 * @author Administrador
 */
public class TrocaSenha extends javax.swing.JFrame
{
    private static final long serialVersionUID = 1L;

    /** Creates new form TrocaSenha */
    public TrocaSenha()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painel = new javax.swing.JPanel();
        botaoAlterarSenha = new javax.swing.JButton();
        campoNovaSenha = new javax.swing.JPasswordField();
        labelNovaSenha = new javax.swing.JLabel();
        labelRepetirSenha = new javax.swing.JLabel();
        campoRepetirSenha = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SiSCOM - Trocar Senha");

        painel.setBackground(new java.awt.Color(255, 255, 255));

        botaoAlterarSenha.setFont(new java.awt.Font("Times New Roman", 1, 14));
        botaoAlterarSenha.setText("Alterar Senha");
        botaoAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarSenhaActionPerformed(evt);
            }
        });
        getRootPane().setDefaultButton(botaoAlterarSenha);

        labelNovaSenha.setFont(new java.awt.Font("Times New Roman", 1, 14));
        labelNovaSenha.setText("Nova Senha");

        labelRepetirSenha.setFont(new java.awt.Font("Times New Roman", 1, 14));
        labelRepetirSenha.setText("Repetir Nova Senha");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(botaoAlterarSenha))
                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(painelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(labelRepetirSenha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(labelNovaSenha)
                            .addGap(42, 42, 42)
                            .addComponent(campoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        painelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoNovaSenha, campoRepetirSenha});

        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(campoRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(botaoAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        painelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoNovaSenha, campoRepetirSenha});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-317)/2, (screenSize.height-178)/2, 317, 178);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoAlterarSenhaActionPerformed
    {//GEN-HEADEREND:event_botaoAlterarSenhaActionPerformed

        String senhaNova = String.valueOf(campoNovaSenha.getPassword());
        String confirma = String.valueOf(campoRepetirSenha.getPassword());

        //nao permite campos em branco.
        if((senhaNova.equalsIgnoreCase("") || confirma.equalsIgnoreCase("")))
        {
            SystemUtil.showErrorMsg("todos os campos devem ser preenchidos",true);
            resetCampos();
            return;
        }

        if(!senhaNova.equalsIgnoreCase(confirma))
        {
            SystemUtil.showErrorMsg("as senhas digitadas nao confirmam!",true);
            resetCampos();
            return;
        }
        else
        {
            DatabaseManager.changePassword(senhaNova);
        dispose();
        }
    }//GEN-LAST:event_botaoAlterarSenhaActionPerformed

    private void resetCampos()
    {
        campoNovaSenha.setText("");
        campoRepetirSenha.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new TrocaSenha().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarSenha;
    private javax.swing.JPasswordField campoNovaSenha;
    private javax.swing.JPasswordField campoRepetirSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNovaSenha;
    private javax.swing.JLabel labelRepetirSenha;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
