/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siscomercio.utilities;

import com.siscomercio.controller.managers.ExceptionManager;
import com.siscomercio.standards.StringTable;
import java.awt.EventQueue;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class FrameLog extends JFrame
{
    File f = new File(StringTable.getLOG_FILE());

    private void le()
    {

        //limpa a area de log para que tenha apenas uma leitura do arquivo na tela
        if (!areaLog.getText().isEmpty())
        {
            areaLog.setText(StringTable.getEMPTY_STRING());
        }

        //verifica a existencia do arquivo de log..
        if (!f.exists())
        {
            Utilitarios.showErrorMessage("O Arquivo : " + f.getPath() + " Nao Existe!");
        }
        else
        {
            try
            {
                RandomAccessFile raf = new RandomAccessFile(f, "rw");

                //verifica se a dados a serem mostrados
                if (raf.length() == 0)
                {
                    Utilitarios.showInfoMessage("Arquivo de Log Vazio!");
                    raf.close();
                }
                else
                {
                    //preseguimos com a leitura..
                    String dados;

                    try (BufferedReader in = new BufferedReader(new FileReader(f.getPath())))
                    {
                        while ((dados = in.readLine()) != null)
                        {
                            areaLog.append(dados + "\n");
                        }
                    }
                    catch (IOException erro)
                    {
                        ExceptionManager.ThrowException("Erro: ", erro);
                    }
                }
            }
            catch (IOException ex)
            {
                Logger.getLogger(FrameLog.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    /**
     * Creates new form FrameLog
     */
    public FrameLog()
    {
        initComponents();
        le();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        areaLog.setColumns(20);
        areaLog.setRows(5);
        jScrollPane1.setViewportView(areaLog);

        jLabel1.setText("Log do Sistema");

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jButton1)
                                .addGap(27, 27, 27)
                                .addComponent(jButton2)))
                        .addGap(0, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(663, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        le();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpa();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limpa()
    {
        areaLog.setText(StringTable.getEMPTY_STRING());
        Utilitarios.zeraArquivo(f);
        le();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Create and display the form
         */
        EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new FrameLog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaLog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
